# Generated by Django 5.0.4 on 2024-05-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat', '0004_resource_is_it_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_it_free',
            field=models.TextField(choices=[('F', 'Free'), ('P', 'Paid')]),
        ),
    ]
