# Generated by Django 5.0.4 on 2024-05-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcat_redditpost_link', models.CharField(blank=True, max_length=2083)),
                ('dat_redditpost_link', models.CharField(blank=True, max_length=2083)),
            ],
        ),
    ]
