# Generated by Django 5.0.4 on 2024-05-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=400)),
                ('material_link', models.CharField(max_length=2083)),
                ('web_link', models.CharField(max_length=2083)),
            ],
        ),
    ]
