# Generated by Django 5.0.4 on 2024-05-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcat', '0003_alter_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_it_free',
            field=models.BooleanField(default=True),
        ),
    ]
